# Note that pr2_analyzers_no_arms_diff.launch also contains some deletions
# that need to be done.

analyzers:
  joints:
    type: GenericAnalyzer
    path: Joints
    startswith: [
      'Joint']
    expected: [
      'Joint (bl_caster_l_wheel_joint)',
      'Joint (bl_caster_r_wheel_joint)',
      'Joint (bl_caster_rotation_joint)',
      'Joint (br_caster_l_wheel_joint)',
      'Joint (br_caster_r_wheel_joint)',
      'Joint (br_caster_rotation_joint)',
      'Joint (fl_caster_l_wheel_joint)',
      'Joint (fl_caster_r_wheel_joint)',
      'Joint (fl_caster_rotation_joint)',
      'Joint (fr_caster_l_wheel_joint)',
      'Joint (fr_caster_r_wheel_joint)',
      'Joint (fr_caster_rotation_joint)',
      'Joint (laser_tilt_mount_joint)',
      'Joint (head_pan_joint)',
      'Joint (head_tilt_joint)',
      'Joint (torso_lift_joint)']

