analyzers:
  joints:
    type: GenericAnalyzer
    path: Joints
    startswith: [
      'Joint']
    expected: [
      'Joint (bl_caster_l_wheel_joint)',
      'Joint (bl_caster_r_wheel_joint)',
      'Joint (bl_caster_rotation_joint)',
      'Joint (br_caster_l_wheel_joint)',
      'Joint (br_caster_r_wheel_joint)',
      'Joint (br_caster_rotation_joint)',
      'Joint (fl_caster_l_wheel_joint)',
      'Joint (fl_caster_r_wheel_joint)',
      'Joint (fl_caster_rotation_joint)',
      'Joint (fr_caster_l_wheel_joint)',
      'Joint (fr_caster_r_wheel_joint)',
      'Joint (fr_caster_rotation_joint)',
      'Joint (head_pan_joint)',
      'Joint (head_tilt_joint)',
      'Joint (laser_tilt_mount_joint)',
      'Joint (torso_lift_joint)',
      'Joint (r_gripper_joint)',
      'Joint (r_wrist_flex_joint)',
      'Joint (r_wrist_roll_joint)',
      'Joint (r_forearm_roll_joint)',
      'Joint (r_elbow_flex_joint)',
      'Joint (r_upper_arm_roll_joint)',
      'Joint (r_shoulder_lift_joint)',
      'Joint (r_shoulder_pan_joint)',
      'Joint (l_gripper_joint)',
      'Joint (l_wrist_flex_joint)',
      'Joint (l_wrist_roll_joint)',
      'Joint (l_forearm_roll_joint)',
      'Joint (l_elbow_flex_joint)',
      'Joint (l_upper_arm_roll_joint)',
      'Joint (l_shoulder_lift_joint)',
      'Joint (l_shoulder_pan_joint)']
    
